name: 'Hello world Slack'
description: 'Slack msg'
inputs:
  token:
    description: 'Slack token'
    required: true
  channels:
    description: 'Slack channels'
    required: true
  message:
    description: 'PR Number'
    required: true
runs:
  using: 'node16'
  main: 'index.js'

